# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :amazonlinux_on_aws do |amazonlinux_on_aws|
    amazonlinux_on_aws.vm.provider :aws do |aws, override|
      # This VM specific settings
      # （VM 固有設定）
      aws.tags = ["name:amazonlinux-on-aws", "environments:development"]
      aws.instance_type = "t1.micro" # CPU:2ECU x1, Memory size:613MiB
      aws.ami = "ami-173fbf16" # "Amazon Linux 2013.03 minimal"
      aws.security_groups = ["default"]

      # AWS provider common settings
      # （AWSプロバイダー共通設定）
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_KEY']
      aws.region = "ap-northeast-1" # "Tokyo"
      aws.availability_zone = "ap-northeast-1a"
      aws.keypair_name = "yattomaws"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "C:/Users/t-yasui/etc/yattomaws.pem"
      aws.user_data = File.read("user_data.txt")
    end

    # Box settings
    # （ボックス設定）
    # Remarks: This is a dummy box for AWS plug-in.
    # （備考: AWSプラグイン用のダミーBoxです。）
    amazonlinux_on_aws.vm.box = "dummy"
    amazonlinux_on_aws.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    amazonlinux_on_aws.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.run_list = "recipe[dummy]"
    end

  end
end

